"""
Plotting code for the PSF size versus pupil radius
Plots the .npy file generated by PSF_size.py
"""
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import PSF as psf

arr = np.load('PSF_size.npy')
plt.scatter(arr[0], arr[1])

rs = np.linspace(arr[0][0], arr[0][-1], 1000)

plt.plot(rs, 1.22/(2*rs))
plt.legend(['Computational', 'Theoretical'])

plt.ylabel(r'Location of 1st minimum ($ \theta / \lambda$)')
plt.xlabel('Circular Pupil Radius (m)')
plt.show()
