"""
Plotting code for the PSF size versus pupil radius
Plots the .npy file generated by PSF_size.py
"""
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import PSF as psf

arr = np.load('PSF_size.npy')
plt.scatter(arr[0], arr[1])

plt.plot(arr[0], 1.029/(2*arr[0]))

plt.legend(['Computational', 'Theoretical'])

plt.ylabel(r'PSF Width at 1/2 Max ($ \theta / \lambda$)')
plt.xlabel('Circular Pupil Radius (m)')
plt.show()
